name: vakinha_burger_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  dotenv: ^3.0.0
  mysql1: ^0.19.2
  shelf_static: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
  build_runner: ^2.1.4
  shelf_router_generator: ^1.0.1
